Move losetup/dmsetup to choose_partition/crypto/do_option
r31607

diff --git a/choose_partition/crypto/do_option b/choose_partition/crypto/do_option
--- a/choose_partition/crypto/do_option
+++ b/choose_partition/crypto/do_option
@@ -245,7 +245,105 @@ create_keyfile () {
     return 0
 }
 
-# Create keys
+get_free_loop () {
+    O=$IFS
+    IFS="
+"
+    for n in $(losetup-aes -a); do
+        n=${n%%:*}
+        n=${n#/dev/loop}
+        n=${n#/}
+        eval loop$n=1
+    done
+    IFS=$O
+
+    for n in 0 1 2 3 4 5 6 7; do
+        if eval [ -z "\$loop$n" ]; then
+            echo $n
+            break
+        fi
+    done
+}
+
+setup_loopaes () {
+    local loop device cipher keyfile opts pass
+    loop=$1
+    device=$2
+    cipher=$3
+    keyfile=$4
+
+    [ -x /sbin/losetup-aes ] || return 1
+
+    if [ $keyfile ]; then
+        opts="-K $keyfile"
+        pass="$keyfile.pass"
+    else
+        # random key
+        opts="-H random"
+        pass="/dev/null"
+    fi
+
+    log-output -t partman-crypto /sbin/losetup-aes -e $cipher $opts -p0 $loop $device -G / < $pass
+    if [ $? -ne 0 ] ; then
+        log "losetup failed"
+        return 2
+    fi
+
+    return 0
+}
+
+setup_dmcrypt () {
+    : TODO
+}
+
+setup_luks () {
+    : TODO
+}
+
+setup_crypt_device () {
+    local type realdev cipher keytype cryptdev
+    type=$1
+    realdev=$2
+    cipher=$3
+    keytype=$4
+
+    case $type in
+        dm-crypt)
+          # TODO: crypt_name ?
+          cryptdev=/dev/mapper/XXX
+          setup_dmcrypt $cryptdev $realdev $cipher || return 1
+          ;;
+
+        dm-crypt-luks)
+          # TODO: crypt_name ?
+          cryptdev=/dev/mapper/ZZZ
+          setup_luks $cryptdev $realdev $cipher || return 1
+          ;;
+      
+        loop-AES)
+          loop=$(get_free_loop);
+          [ -z "$loop" ] && return 1
+          cryptdev=/dev/loop/$loop
+
+          case $keytype in
+            random)
+              keyfile=""
+              ;;
+            keyfile)
+              keyfile=$(cat $id/keyfile)
+              ;;
+          esac
+
+          setup_loopaes $cryptdev $realdev $cipher $keyfile || return 1
+          ;;
+
+    esac
+
+    echo $cryptdev > $dev/$id/crypt_active
+    return 0
+}
+
+# Create keys and do losetup/dmsetup
 
 for dev in $DEVICES/*; do
     [ -d "$dev" ] || continue
@@ -270,9 +368,11 @@ for dev in $DEVICES/*; do
         [ -f $id/cipher ] || continue
         [ -f $id/keytype ] || continue
 
-	keytype=$(cat $id/keytype)
+        type=$(cat $id/crypt_type)
+        keytype=$(cat $id/keytype)
+        cipher=$(cat $id/cipher)
 
-	if [ $keytype = keyfile ]; then
+        if [ $keytype = keyfile ]; then
             keyfile=$id/$(keyfile_name $path)
 
             if [ ! -f $keyfile ]; then
@@ -281,12 +381,24 @@ for dev in $DEVICES/*; do
                     db_fset partman-crypto/commit_failed seen false
                     db_input critical partman-crypto/commit_failed
                     db_go || true
-		    failed=1
-		    break
+                    failed=1
+                    break
                 fi
             fi
 
-	    echo $keyfile > $id/keyfile
+            echo $keyfile > $id/keyfile
+        fi
+
+        if [ ! -f $id/crypt_active ]; then
+            log "creating crypt_disk for $path"
+
+            if ! setup_crypt_device $type $path $cipher $keytype; then
+                db_fset partman-crypto/commit_failed seen false
+                db_input critical partman-crypto/commit_failed
+                db_go || true
+                failed=1
+                break
+            fi
         fi
     done
 done
